resolver: lts-13.28

packages:
  - apecs
  - apecs-physics
  - apecs-gloss
  - apecs-stm
  - examples

extra-deps:
  - stm-containers-1.1.0.2
  - stm-hamt-1.2.0.2
  - primitive-extras-0.7.1

nix:
  pure: false
  packages:
    - libGL
    - freeglut
    - mesa_glu
    - zlib
